# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "master" do |master|
      master.vm.box= "centos/8"
      master.vm.hostname="master"
      master.vm.network "private_network", ip: "192.168.33.10"
    end
   
   config.vm.define "web" do |web|
    web.vm.box = "centos/8"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "bdd" do |bdd|
    bdd.vm.box = "centos/8"
    bdd.vm.hostname = "bdd"
    bdd.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = "4048"
    v.cpus = "2"
  end

end